### ISSUE TITLE
Explanation of  some Variables 

### ISSUE THREAD

**Issue by SerpentDrago** [membersheep/telegram-mumble-bot#2]
what should i use for 

WEBHOOK_PATH 

WEBHOOK_BASE_URL  

My limited understanding has me believe this has something to do with the Heroku app URL , that will hopefully keep the bot alive ? as i notice it idles and quits after a certain period of time ? 

as of now i have nothing in them and it idles out . but if i refresh the app url  ( https://appname.herokuapp.com   it will stay up . 

PS: Additional Requests 
*Limited commands would be amazing . so you could message the bot in the channel and get a current mumble user list ? 
*have the bot ignore itself when listing members on mumble server ? 

Thanks man . I don't really program and I dont' want to ask for to much . I just take peoples codes and try to use them . so Thanks for the bot man ! I've tried to figure out as much as i can without pestering you !

**Comment by membersheep** [comment]
Hi,
I will write a brief guide explaining the configuration in the readme, as soon as I can.
The bot idles automatic because of heroku, you have to pay for the service for it to work 24/7. When the bot goes idle it disconnects from Mumble. When you send the bot a request it wakes up, connects to mumble, and posts a message to your chat (if configured to do so). 
There is already a command to get the connected users list (/mumble) and I can easily update it to exclude "bot" from the list. You can also post messages in telegram chat from mumble by sending mumble text messages directly to the bot.

**Comment by membersheep** [comment]
Updated readme with brief variables explanation in df75712.
